\sloppy
* Meta-data :noexport:
  # http://orgmode.org/worg/exporters/beamer/tutorial.html
  #+TITLE: Equivalence of G-formula and IPTW
  #+AUTHOR: Kazuki Yoshida @@latex:\\@@
  #+AUTHOR: @@latex:\\@@
  #+AUTHOR: \faTwitter [[https://twitter.com/kaz_yos][@kaz_yos]] \faGithub [[https://github.com/kaz-yos/][kaz-yos]]
  #+DATE: \today@@latex:\\@@
  #+DESCRIPTION:
  #+KEYWORDS:
  #+OPTIONS: toc:nil
  #+OPTIONS: H:2
  #+OPTIONS: ^:{}
  # LATEX configurations
  #+LATEX_CLASS_OPTIONS: [dvipdfmx,10pt]
  #+LATEX_HEADER: %% Margin
  #+LATEX_HEADER: %% \usepackage[margin=1.5cm]{geometry}
  #+LATEX_HEADER: \usepackage[top=1.5cm, bottom=1.5cm, left=1.5cm, right=1.5cm, headsep=4pt]{geometry}
  #+LATEX_HEADER: %% \addtolength{\topmargin}{0.3cm}
  #+LATEX_HEADER: %% \addtolength{\textheight}{1.75in}
  #+LATEX_HEADER: %% Math
  #+LATEX_HEADER: \usepackage{amsmath}
  #+LATEX_HEADER: \usepackage{amssymb}
  #+LATEX_HEADER: \usepackage{wasysym}
  #+LATEX_HEADER: %% Allow new page within align
  #+LATEX_HEADER: \allowdisplaybreaks
  #+LATEX_HEADER: \usepackage{cancel}
  #+LATEX_HEADER: % % Code
  #+LATEX_HEADER: \usepackage{listings}
  #+LATEX_HEADER: \usepackage{courier}
  #+LATEX_HEADER: \lstset{basicstyle=\footnotesize\ttfamily, breaklines=true, frame=single}
  #+LATEX_HEADER: \usepackage[cache=false]{minted}
  #+LATEX_HEADER: \usemintedstyle{vs}
  #+LATEX_HEADER: %% Graphics
  #+LATEX_HEADER: \usepackage{graphicx}
  #+LATEX_HEADER: \usepackage{grffile}
  #+LATEX_HEADER: %% DAG
  #+LATEX_HEADER: \usepackage{tikz}
  #+LATEX_HEADER: \usetikzlibrary{positioning,shapes.geometric}
  #+LATEX_HEADER: %% Date
  #+LATEX_HEADER: \usepackage[yyyymmdd]{datetime}
  #+LATEX_HEADER: \renewcommand{\dateseparator}{--}
  #+LATEX_HEADER: %% Header
  #+LATEX_HEADER: \usepackage{fancyhdr}
  #+LATEX_HEADER: \pagestyle{fancy}
  #+LATEX_HEADER: \fancyhf{} % Erase first to supress section names
  #+LATEX_HEADER: \fancyhead[L]{Kazuki Yoshida} % LEFT
  #+LATEX_HEADER: \fancyhead[C]{} % CENTER
  #+LATEX_HEADER: \fancyhead[R]{\today} % RIGHT
  #+LATEX_HEADER: \fancyfoot[C]{\thepage}
  #+LATEX_HEADER: %% \fancyfoot[R]{Page \thepage\ of \pageref{LastPage}}
  #+LATEX_HEADER: %% Section font size
  #+LATEX_HEADER: \usepackage{sectsty}
  #+LATEX_HEADER: \sectionfont{\small}
  #+LATEX_HEADER: \subsectionfont{\small}
  #+LATEX_HEADER: \subsubsectionfont{\small}
  #+LATEX_HEADER: %% Section numbering
  #+LATEX_HEADER: %% http://tex.stackexchange.com/questions/3177/how-to-change-the-numbering-of-part-chapter-section-to-alphabetical-r
  #+LATEX_HEADER: %% \renewcommand\thesection{\alph{section}}
  #+LATEX_HEADER: %% \renewcommand\thesubsection{\thesection.\arabic{subsection}}
  #+LATEX_HEADER: %% \renewcommand{\thesubsubsection}{\thesubsection.\alph{subsubsection}}
  #+LATEX_HEADER: %%
  #+LATEX_HEADER: %% http://tex.stackexchange.com/questions/40067/numbering-sections-with-sequential-integers
  #+LATEX_HEADER: %% \usepackage{chngcntr}
  #+LATEX_HEADER: %% \counterwithout{subsection}{section}
  #+LATEX_HEADER: %% enumerate
  #+LATEX_HEADER: \usepackage{enumerate}
  #+LATEX_HEADER: %% double space
  #+LATEX_HEADER: %% \usepackage{setspace}
  #+LATEX_HEADER: %% \linespread{2}
  #+LATEX_HEADER: %% Paragraph Indentation
  #+LATEX_HEADER: \usepackage{indentfirst}
  #+LATEX_HEADER: \setlength{\parindent}{0em}
  #+LATEX_HEADER: %% Spacing after headings
  #+LATEX_HEADER: %% http://tex.stackexchange.com/questions/53338/reducing-spacing-after-headings
  #+LATEX_HEADER: \usepackage{titlesec}
  #+LATEX_HEADER: \titlespacing      \section{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
  #+LATEX_HEADER: \titlespacing   \subsection{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
  #+LATEX_HEADER: \titlespacing\subsubsection{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
  #+LATEX_HEADER: %% Fix figures and tables by [H]
  #+LATEX_HEADER: \usepackage{float}
  #+LATEX_HEADER: %% Allow URL embedding
  #+LATEX_HEADER: \usepackage{url}
  #+LATEX_HEADER: \usepackage{fontawesome}
  #+LATEX_HEADER: \input{\string~/.emacs.d/misc/GrandMacros}
  # ############################################################################ #

* INTRODUCTION
** IPTW and G-formula
- Here we will demonstrate the equivalence of the IPTW cite:robinsMarginalStructuralModels2000 and the /g/-formula cite:robinsNewApproachCausal1986 given saturated models.
- Special thanks to [[https://twitter.com/edwardhkennedy/status/1119305663564472320][@edwardhkennedy]]!

** Notations
\begin{align*}
  Y &: \text{Outcome measured at the end of the study}\\
  Y^{a_{0}} &: \text{Counterfactual outcome with intervention at time 0 only}\\
  Y^{a_{0},a_{1}} &: \text{Counterfactual outcome with intervention at time 0 and 1}\\
  L_{0} &: \text{Baseline covariates}\\
  A_{0} &: \text{Baseline treatment assignment}\\
  L_{1} &: \text{Post-baseline covariates}\\
  A_{1} &: \text{Post-baseline treatment assignment}\\
\end{align*}

Here we assume both $L_{t}$ and $A_{t}$ are discrete.

** Causal structure
*** Original DAG
\begin{center}
\begin{tikzpicture}[%
  ->,
  shorten >=2pt,
  >=stealth,
  node distance=1cm,
  pil/.style={
    ->,
    thick,
    shorten =2pt,}
  ]
  %% Nodes
  \node (L0) {$L_{0}$};
  \node[right = 1cm of L0] (A0) {$A_{0}$};
  \node[right = 1cm of A0] (L1) {$L_{1}$};
  \node[right = 1cm of L1] (A1) {$A_{1}$};
  \node[right = 1cm of A1] (Y) {$Y$};
  %% Edges
  \draw[->] (L0) to (A0);
  \draw[->] (L0) to [out=25,in=155] (L1);
  \draw[->] (L0) to [out=25,in=155] (A1);
  \draw[->] (L0) to [out=25,in=155] (Y);
  \draw[->] (A0) to (L1);
  \draw[->] (A0) to [out=-25,in=-155] (A1);
  \draw[->] (A0) to [out=-25,in=-155] (Y);
  \draw[->] (L1) to (A1);
  \draw[->] (L1) to [out=-25,in=-155] (Y);
  \draw[->] (A1) to (Y);
\end{tikzpicture}
\end{center}

*** Single time point intervention SWIG
\begin{center}
\begin{tikzpicture}[%
  ->,
  shorten >=2pt,
  >=stealth,
  node distance=1cm,
  pil/.style={
    ->,
    thick,
    shorten =2pt,}
  ]
  %% Nodes
  \node (L0) {$L_{0}$};
  \node[right = 1cm of L0] (A0) {$A_{0}||a_{0}$};
  \node[right = 1cm of A0] (L1) {$L_{1}^{a_{0}}$};
  \node[right = 1cm of L1] (A1) {$A_{1}^{a_{0}}$};
  \node[right = 1cm of A1] (Y) {$Y^{a_{0}}$};
  %% Edges
  \draw[->] (L0) to (A0);
  \draw[->] (L0) to [out=25,in=155] (L1);
  \draw[->] (L0) to [out=25,in=155] (A1);
  \draw[->] (L0) to [out=25,in=155] (Y);
  \draw[->] (A0) to (L1);
  \draw[->] (A0) to [out=-25,in=-155] (A1);
  \draw[->] (A0) to [out=-25,in=-155] (Y);
  \draw[->] (L1) to (A1);
  \draw[->] (L1) to [out=-25,in=-155] (Y);
  \draw[->] (A1) to (Y);
\end{tikzpicture}
\end{center}

*** Two time point intervention SWIG
\begin{center}
\begin{tikzpicture}[%
  ->,
  shorten >=2pt,
  >=stealth,
  node distance=1cm,
  pil/.style={
    ->,
    thick,
    shorten =2pt,}
  ]
  %% Nodes
  \node (L0) {$L_{0}$};
  \node[right = 1cm of L0] (A0) {$A_{0}||a_{0}$};
  \node[right = 1cm of A0] (L1) {$L_{1}^{a_{0}}$};
  \node[right = 1cm of L1] (A1) {$A_{1}^{a_{0}}||a_{1}$};
  \node[right = 1cm of A1] (Y) {$Y^{a_{0},a_{1}}$};
  %% Edges
  \draw[->] (L0) to (A0);
  \draw[->] (L0) to [out=25,in=155] (L1);
  \draw[->] (L0) to [out=25,in=155] (A1);
  \draw[->] (L0) to [out=25,in=155] (Y);
  \draw[->] (A0) to (L1);
  \draw[->] (A0) to [out=-25,in=-155] (A1);
  \draw[->] (A0) to [out=-25,in=-155] (Y);
  \draw[->] (L1) to (A1);
  \draw[->] (L1) to [out=-25,in=-155] (Y);
  \draw[->] (A1) to (Y);
\end{tikzpicture}
\end{center}


* Single time point strategy
** Identifiability Conditions
- We will follow the terminologies in cite:hernanCausalInference2019 (Chapter 3).
- 1. *Consistency*: the values of treatment under comparison correspond to well-defined interventions that, in turn, correspond to the versions of treatment in the data
#+BEGIN_CENTER
$Y_{i} = Y_{i}^{a_{0}}$ if $A_{0i} = a_{0}$ for all $a_{0}$
#+END_CENTER
- 2. *Exchangeability*: the conditional probability of receiving every value of treatment, though not decided by the investigators, depends only on the measured covariates
#+BEGIN_CENTER
$A_{0} \ind Y^{a_{0}} | L_{0}$ for all $a_{0}$
#+END_CENTER
- 3. *Positivity*: the conditional probability of receiving every value of treatment is greater than zero, i.e., positive
#+BEGIN_CENTER
$f(A_{0} = a_{0} | L_{0} = l_{0}) > 0$ for all $a_{0},l_{0}$ where $f(L_{0} = l_{0}) > 0$
#+END_CENTER

** G-formula
   :PROPERTIES:
   :BEAMER_opt: allowframebreaks,label=,t
   :END:
This follows the Technical Point 2.3 in cite:hernanCausalInference2019.
\begin{align*}
  &~~~\text{By iterative expectation}\\
  E[Y^{a_{0}}]
  &= E[E[Y^{a_{0}} | L_{0}]]\\
  &~~~\text{By conditional exchangeability: } Y^{a_{0}} \ind A_{0} | L_{0}\\
  &= E[E[Y^{a_{0}} | A_{0}, L_{0}]]\\
  &~~~\text{By exchangeability, }E[Y^{a_{0}} | A_{0}, L_{0}] = E[Y^{a_{0}} | A_{0} = a_{0}, L_{0}]\\
  &= E[E[Y^{a_{0}} | A_{0} = a_{0}, L_{0}]]\\
  &~~~\text{By consistency}\\
  &= E[E[Y | A_{0} = a_{0}, L_{0}]]\\
  &~~~\text{Make outer expectation explicit sum}\\
  &= \sum_{l_{0}} E[Y | A_{0} = a_{0}, L_{0} = l_{0}] f(L_{0} = l_{0})\\
  &= \text{Conditional mean averaged over $L_{0}$}\\
\end{align*}

** IPTW
   :PROPERTIES:
   :BEAMER_opt: allowframebreaks,label=,t
   :END:
This follows the Technical Point 2.3 in cite:hernanCausalInference2019.
\begin{align*}
  &~~~\text{By iterative expectation}\\
  E[Y^{a_{0}}]
  &= E[E[Y^{a_{0}} | L_{0}]]\\
  &~~~\text{Insert a carefully-crafted expression that is 1.}\\
  &= E \left[ \frac{f(A_{0}=a_{0} | L_{0})}{f(A_{0}=a_{0} | L_{0})} E[Y^{a_{0}} | L_{0}] \right]\\
  &~~~\text{Using probability = expectation of indicator}\\
  &= E \left[ \frac{E[I(A_{0}=a_{0}) | L_{0}]}{f(A_{0}=a_{0} | L_{0})} E[Y^{a_{0}} | L_{0}] \right]\\
  &~~~\text{Conditional exchangeability: } Y^{a_{0}} \ind A_{0} | L_{0}\\
  &~~~\text{This allows merging the two inner expectations.}\\
  &= E \left[ \frac{1}{f(A_{0}=a_{0} | L_{0})} E[I(A_{0}=a_{0})Y^{a_{0}} | L_{0}] \right]\\
  &~~~\text{By stability, } g(L_{0}) = E[g(L_{0}) | L_{0}].\\
  &~~~\text{i.e., a function of $L_{0}$ only (IPTW expression) can go into $E[\cdot | L_{0}]$}\\
  &= E \left[ E \left[ \frac{1}{f(A_{0}=a_{0} | L_{0})} I(A_{0}=a_{0})Y^{a_{0}} \bigg| L_{0} \right] \right]\\
  &~~~\text{Reversing iterative expectation (tower property)}\\
  &= E \left[ \frac{1}{f(A_{0}=a_{0} | L_{0})} I(A_{0}=a_{0})Y^{a_{0}} \right]\\
  &~~~\text{By consistency, }I(A_{0}=a_{0})Y^{a_{0}} = I(A_{0}=a_{0})Y = Y \text{ for } A_{0} = a_{0}.\\
  &~~~\text{Also, }I(A_{0}=a_{0})Y^{a_{0}} = 0 = I(A_{0}=a_{0})Y \text{ for } A_{0} \ne a_{0}.\\
  &~~~\text{Thus, }I(A_{0}=a_{0})Y^{a_{0}} = I(A_{0}=a_{0})Y \text{ regardless of } A_{0}.\\
  &= E \left[ \frac{1}{f(A_{0}=a_{0} | L_{0})} I(A_{0}=a_{0})Y \right]\\
  &= \text{IPTW mean of $Y$ for group $A_{0} = a_{0}$}\\
\end{align*}

- Law of Total Expectation (Iterative Expectation): https://en.wikipedia.org/wiki/Law_of_total_expectation
- Stability and Tower Property: https://en.wikipedia.org/wiki/Conditional_expectation#Basic_properties
- Indicator function: https://www.statlect.com/fundamentals-of-probability/indicator-functions
- Expectation of product of random variables: https://en.wikipedia.org/wiki/Product_distribution#Expectation_of_product_of_random_variables

* Multiple time point strategy
** Identifiability Conditions
- We will follow the terminologies in cite:hernanCausalInference2019 (Chapter 19, Technical Point 19.2).
- 1. *Consistency*: the values of treatment under comparison correspond to well-defined interventions that, in turn, correspond to the versions of treatment in the data
#+BEGIN_CENTER
$Y_{i} = Y_{i}^{a_{0},a_{1}}$ if $A_{0i} = a_{0}, A_{1i} = a_{1}$ for all $a_{0},a_{1}$
#+END_CENTER
- 2. *Exchangeability*: the conditional probability of receiving every value of treatment, though not decided by the investigators, depends only on the measured covariates
#+BEGIN_CENTER
$A_{0} \ind Y^{a_{0},a_{1}} | L_{0}$ for all $a_{0},a_{1}$

$A_{1} \ind Y^{a_{0},a_{1}} | L_{1},A_{0}=a_{0},L_{0}$ for all $a_{0},a_{1}$
#+END_CENTER
- 3. *Positivity*: the conditional probability of receiving every value of treatment is greater than zero, i.e., positive
#+BEGIN_CENTER
$f(A_{0} = a_{0} | L_{0} = l_{0}) > 0$ for all $a_{0},l_{0}$ where $f(L_{0} = l_{0}) > 0$

$f(A_{1} = a_{1} | L_{1} = l_{1}, A_{0} = a_{0}, L_{0} = l_{0}) > 0$ for all $a_{1},l_{1},a_{0},l_{0}$ where $f(L_{1} = l_{1}, A_{0} = a_{0}, L_{0} = l_{0}) > 0$
#+END_CENTER

** G-formula
   :PROPERTIES:
   :BEAMER_opt: allowframebreaks,label=,t
   :END:
This follows the Technical Point 2.3 in cite:hernanCausalInference2019.
\begin{align*}
  &~~~\text{By iterative expectation}\\
  E[Y^{a_{0},a_{1}}]
  &= E[E[Y^{a_{0},a_{1}} | L_{0}]]\\
  &~~~\text{By conditional exchangeability: } Y^{a_{0},a_{1}} \ind A_{0} | L_{0}\\
  &= E[E[Y^{a_{0},a_{1}} | A_{0}, L_{0}]]\\
  &~~~\text{By exchangeability, }E[Y^{a_{0},a_{1}} | A_{0}, L_{0}] = E[Y^{a_{0},a_{1}} | A_{0} = a_{0}, L_{0}]\\
  &= E[E[Y^{a_{0},a_{1}} | A_{0} = a_{0}, L_{0}]]\\
  &~~~\text{By iterative expectation}\\
  &= E[E[ E[Y^{a_{0},a_{1}} | L_{1}, A_{0} = a_{0}, L_{0}] | A_{0} = a_{0}, L_{0}]]\\
  &~~~\text{By conditional exchangeability: } Y^{a_{0},a_{1}} \ind A_{1} | L_{1},A_{0},L_{0}\\
  &= E[E[ E[Y^{a_{0},a_{1}} | A_{1}, L_{1}, A_{0} = a_{0}, L_{0}] | A_{0} = a_{0}, L_{0}]]\\
  &~~~\text{By exchangeability, }\\
  &~~~E[Y^{a_{0},a_{1}} | A_{1}, L_{1}, A_{0} = a_{0}, L_{0}] = E[Y^{a_{0},a_{1}} | A_{1} = a_{1}, L_{1}, A_{0} = a_{0}, L_{0}]\\
  &= E[E[ E[Y^{a_{0},a_{1}} | A_{1} = a_{1}, L_{1}, A_{0} = a_{0}, L_{0}] | A_{0} = a_{0}, L_{0}]]\\
  &~~~\text{By consistency}\\
  &= E[E[ E[Y | A_{1} = a_{1}, L_{1}, A_{0} = a_{0}, L_{0}] | A_{0} = a_{0}, L_{0}]]\\
  &~~~\text{Make outer expectations explicit sums}\\
  &= \sum_{l_{0}} \sum_{l_{1}}
    E[Y | A_{1} = a_{1}, L_{1} = l_{1}, A_{0} = a_{0}, L_{0} = l_{0}]\\
  &~~~\times f(L_{1} = l_{1} | A_{0} = a_{0}, L_{0} = l_{0}) f(L_{0} = l_{0})\\
\end{align*}

** IPTW
   :PROPERTIES:
   :BEAMER_opt: allowframebreaks,label=,t
   :END:
This follows the Technical Point 2.3 in cite:hernanCausalInference2019 and an input from [[https://twitter.com/edwardhkennedy/status/1119305663564472320][@edwardhkennedy]].
\begin{align*}
  &~~~\text{By iterative expectation}\\
  E\left[Y^{a_{0},a_{1}}\right]
  &= E\left[E\left[Y^{a_{0},a_{1}} | L_{0}\right]\right]\\
  &~~~\text{Insert a carefully-crafted expression that is 1.}\\
  &= E\left[\frac{f(A_{0}=a_{0} | L_{0})}{f(A_{0}=a_{0} | L_{0})} E\left[Y^{a_{0},a_{1}} | L_{0}\right]\right]\\
  &~~~\text{Using probability = expectation of indicator}\\
  &= E\left[\frac{E \left[ I(A_{0}=a_{0}) | L_{0} \right]}{f(A_{0}=a_{0} | L_{0})} E\left[Y^{a_{0},a_{1}} | L_{0}\right]\right]\\
  &~~~\text{By conditional exchangeability: } Y^{a_{0},a_{1}} \ind A_{0} | L_{0}\\
  &~~~\text{Thus, product of expectation = expectation of product}\\
  &= E\left[\frac{1}{f(A_{0}=a_{0} | L_{0})} E\left[I(A_{0}=a_{0})Y^{a_{0},a_{1}} | L_{0}\right]\right]\\
  &~~~\text{Law of total expectation}\\
  &= E\left[
    \frac{1}{f(A_{0}=a_{0} | L_{0})} E\left[I(A_{0}=a_{0})Y^{a_{0},a_{1}} | A_{0}=a_{0}, L_{0}\right]
    \right.\\
  &~~~~~~~~+\left.
    \frac{1}{f(A_{0}=a_{0} | L_{0})} E\left[I(A_{0}=a_{0})Y^{a_{0},a_{1}} | A_{0}\ne a_{0}, L_{0}\right]
    \right]\\
  &~~~\text{Indicator in second inner expectation = 0}\\
  &= E\left[\frac{1}{f(A_{0}=a_{0} | L_{0})} E\left[I(A_{0}=a_{0})Y^{a_{0},a_{1}} | A_{0} = a_{0}, L_{0}\right]\right]\\
  &~~~\text{By iterative expectation}\\
  &= E\left[\frac{1}{f(A_{0}=a_{0} | L_{0})} E\left[E\left[I(A_{0}=a_{0})Y^{a_{0},a_{1}} |L_{1}, A_{0} = a_{0}, L_{0}\right] | A_{0} = a_{0}, L_{0}\right]\right]\\
  &~~~\text{Insert a carefully-crafted expression that is 1.}\\
  &= E\left[\frac{1}{f(A_{0}=a_{0} | L_{0})}\times\right.\\
  &~~~~~~~\left.
    E\left[ \frac{f(A_{1}=a_{1} | L_{1}, A_{0} = a_{0}, L_{0})}{f(A_{1}=a_{1} | L_{1}, A_{0} = a_{0}, L_{0})}
    E\left[I(A_{0}=a_{0})Y^{a_{0},a_{1}} |L_{1}, A_{0} = a_{0}, L_{0}\right] \bigg| A_{0} = a_{0}, L_{0}\right]\right]\\
  &~~~\text{Using probability = expectation of indicator}\\
  &= E\left[\frac{1}{f(A_{0}=a_{0} | L_{0})}\times\right.\\
  &~~~~~~~\left.
    E\left[ \frac{E \left[ I(A_{1}=a_{1}) | L_{1}, A_{0} = a_{0}, L_{0} \right]}{f(A_{1}=a_{1} | L_{1}, A_{0} = a_{0}, L_{0})}
    E\left[I(A_{0}=a_{0})Y^{a_{0},a_{1}} |L_{1}, A_{0} = a_{0}, L_{0}\right] \bigg| A_{0} = a_{0}, L_{0}\right]\right]\\
  &~~~\text{By conditional exchangeability: } Y^{a_{0},a_{1}} \ind A_{1} | L_{1},A_{0} = a_{0},L_{0}\\
  &~~~\text{Thus, product of expectation = expectation of product}\\
  &= E\left[\frac{1}{f(A_{0}=a_{0} | L_{0})}\times\right.\\
  &~~~~~~~\left.
    E\left[ \frac{E\left[I(A_{0}=a_{0})I(A_{1}=a_{1})Y^{a_{0},a_{1}} |L_{1}, A_{0} = a_{0}, L_{0}\right]}{f(A_{1}=a_{1} | L_{1}, A_{0} = a_{0}, L_{0})}
     \bigg| A_{0} = a_{0}, L_{0}\right]\right]\\
  &~~~\text{IPTW at time 1 is a constant given }L_{1}, A_{0} = a_{0}, L_{0}\\
  &= E\left[\frac{1}{f(A_{0}=a_{0} | L_{0})}\times\right.\\
  &~~~~~~~\left.
    E\left[
    E\left[\frac{I(A_{0}=a_{0})I(A_{1}=a_{1})Y^{a_{0},a_{1}}}{f(A_{1}=a_{1} | L_{1}, A_{0} = a_{0}, L_{0})} \bigg|L_{1}, A_{0} = a_{0}, L_{0}\right]
     \bigg| A_{0} = a_{0}, L_{0}\right]\right]\\
  &~~~\text{Reverse iterative expectation (tower property)}\\
  &= E\left[\frac{1}{f(A_{0}=a_{0} | L_{0})}
    E\left[
    \frac{I(A_{0}=a_{0})I(A_{1}=a_{1})Y^{a_{0},a_{1}}}{f(A_{1}=a_{1} | L_{1}, A_{0} = a_{0}, L_{0})}
    \bigg| A_{0} = a_{0}, L_{0}\right]\right]\\
  &~~~\text{Add a second term that is zero by indicator }I(A_{0}=a_{0})\\
  &= E\left[\frac{1}{f(A_{0}=a_{0} | L_{0})}
    E\left[\frac{I(A_{0}=a_{0})I(A_{1}=a_{1})Y^{a_{0},a_{1}}}{f(A_{1}=a_{1} | L_{1}, A_{0} = a_{0}, L_{0})} \bigg| A_{0} = a_{0}, L_{0}\right]
    \right.\\
  &~~~~~~~\left. +\frac{1}{f(A_{0}=a_{0} | L_{0})}
  E\left[\frac{I(A_{0}=a_{0})I(A_{1}=a_{1})Y^{a_{0},a_{1}}}{f(A_{1}=a_{1} | L_{1}, A_{0} = a_{0}, L_{0})} \bigg| A_{0} \ne a_{0}, L_{0}\right]
\right]\\
  &~~~\text{Thus, we can drop conditioning on $A_{0}$.}\\
  &= E\left[\frac{1}{f(A_{0}=a_{0} | L_{0})}
    E\left[
    \frac{I(A_{0}=a_{0})I(A_{1}=a_{1})Y^{a_{0},a_{1}}}{f(A_{1}=a_{1} | L_{1}, A_{0} = a_{0}, L_{0})}
    \bigg| L_{0}\right]\right]\\
  &~~~\text{IPTW at time 0 is a constant given }L_{0}\\
  &= E\left[
    E\left[
    \frac{I(A_{0}=a_{0})I(A_{1}=a_{1})Y^{a_{0},a_{1}}}{f(A_{0}=a_{0} | L_{0})f(A_{1}=a_{1} | L_{1}, A_{0} = a_{0}, L_{0})}
    \bigg| L_{0}\right]\right]\\
  &~~~\text{Reverse iterative expectation (tower property)}\\
  &= E\left[
    \frac{I(A_{0}=a_{0})I(A_{1}=a_{1})Y^{a_{0},a_{1}}}{f(A_{0}=a_{0} | L_{0})f(A_{1}=a_{1} | L_{1}, A_{0} = a_{0}, L_{0})}
    \right]\\
  &~~~\text{By consistency and presence of indicators}\\
  &~~~I(A_{0}=a_{0})I(A_{1}=a_{1})Y^{a_{0},a_{1}} = I(A_{0}=a_{0})I(A_{1}=a_{1})Y \text{ for all }A_{0},A_{1}\\
  &~~~\text{That is, consistency where $A_{0}=a_{0},A_{1}=a_{1}$, otherwise both sides are zeros.}\\
  &= E\left[
    \frac{I(A_{0}=a_{0})I(A_{1}=a_{1})Y}{f(A_{0}=a_{0} | L_{0})f(A_{1}=a_{1} | L_{1}, A_{0} = a_{0}, L_{0})}
    \right]\\
  &= \text{IPTW mean of $Y$ for group $A_{0} = a_{0}, A_{1} = a_{1}$}\\
\end{align*}

* Bibliography Part
** Bibliography
# To remove "References" section header
\renewcommand{\section}[2]{}
# Following lines must be left-aligned without preceding spaces.
bibliographystyle:apalike
bibliography:~/.emacs.d/misc/zotero.bib
