\sloppy
* Meta-data :noexport:
  # http://orgmode.org/worg/exporters/beamer/tutorial.html
  #+TITLE: Equivalence of IPTW and G-formula @@latex:\\@@
  #+AUTHOR: Kazuki Yoshida @@latex:\\@@
  #+AUTHOR: @@latex:\\@@
  #+AUTHOR: \faTwitter @kaz_yos \faGithub kaz-yos
  #+DATE: \today@@latex:\\@@
  #+DESCRIPTION:
  #+KEYWORDS:
  #+OPTIONS: toc:nil
  #+OPTIONS: H:2
  #+OPTIONS: ^:{}
  #+STARTUP: beamer
  #+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
  #+LATEX_CLASS: beamer
  #+LATEX_CLASS_OPTIONS: [dvipdfmx,bigger,aspectratio=169]
  #+LATEX_HEADER: %% No navigation bar
  #+LATEX_HEADER: \setbeamertemplate{navigation symbols}{}
  #+LATEX_HEADER: %% Page number with current/total format
  #+LATEX_HEADER: \setbeamerfont{page number in head/foot}{size=\scriptsize}
  #+LATEX_HEADER: \setbeamertemplate{footline}[frame number]
  #+LATEX_HEADER: \setbeamertemplate{frametitle}[default][center]
  #+LATEX_HEADER: %% With item labels
  #+LATEX_HEADER: \setbeamertemplate{bibliography item}{\insertbiblabel}
  #+LATEX_HEADER: %% Without item labels
  #+LATEX_HEADER: %% \setbeamertemplate{bibliography item}{}
  #+LATEX_HEADER:
  #+LATEX_HEADER: %% Math
  #+LATEX_HEADER: \usepackage{amsmath}
  #+LATEX_HEADER: \usepackage{amssymb}
  #+LATEX_HEADER: \usepackage{wasysym}
  #+LATEX_HEADER: %% Allow new page within align
  #+LATEX_HEADER: \allowdisplaybreaks
  #+LATEX_HEADER: \usepackage{cancel}
  #+LATEX_HEADER: %% Code
  #+LATEX_HEADER: \usepackage{listings}
  #+LATEX_HEADER: \usepackage{courier}
  #+LATEX_HEADER: \lstset{basicstyle=\footnotesize\ttfamily, breaklines=true, frame=single}
  #+LATEX_HEADER: \usepackage[cache=false]{minted}
  #+LATEX_HEADER: \usemintedstyle{vs}
  #+LATEX_HEADER: %% Graphics
  #+LATEX_HEADER: \usepackage{graphicx}
  #+LATEX_HEADER: \usepackage{grffile}
  #+LATEX_HEADER: %% DAG
  #+LATEX_HEADER: \usepackage{tikz}
  #+LATEX_HEADER: \usetikzlibrary{positioning,shapes.geometric}
  #+LATEX_HEADER: %% Allow URL embedding
  #+LATEX_HEADER: \usepackage{url}
  #+LATEX_HEADER: %% Do not count backup slides.
  #+LATEX_HEADER: %% https://tex.stackexchange.com/questions/70448/dont-count-backup-slides
  #+LATEX_HEADER: \usepackage{appendixnumberbeamer}
  #+LATEX_HEADER: %% https://www.sharelatex.com/learn/Hyperlinks
  #+LATEX_HEADER: \usepackage{hyperref}
  #+LATEX_HEADER: \hypersetup{
  #+LATEX_HEADER:     colorlinks = true,
  #+LATEX_HEADER:     linkcolor= blue
  #+LATEX_HEADER: }
  #+LATEX_HEADER: \usepackage{fontawesome}
  #+LATEX_HEADER: %% Include convenient commands.
  #+LATEX_HEADER: \input{\string~/.emacs.d/misc/GrandMacros}
# ############################################################################ #

* INTRODUCTION
** IPTW and G-formula
- Here we will demonstrate the equivalence of the IPTW cite:robinsMarginalStructuralModels2000 and the /g/-formula cite:robinsNewApproachCausal1986 given saturated models.
- Special thanks to [[https://twitter.com/edwardhkennedy/status/1119305663564472320][@edwardhkennedy]]!

** Notations
\begin{align*}
  Y &: \text{Outcome measured at the end of the study}\\
  Y^{a_{0}} &: \text{Counterfactual outcome with intervention at time 0 only}\\
  Y^{a_{0},a_{1}} &: \text{Counterfactual outcome with intervention at time 0 and 1}\\
  L_{0} &: \text{Baseline covariates}\\
  A_{0} &: \text{Baseline treatment assignment}\\
  L_{1} &: \text{Post-baseline covariates}\\
  A_{1} &: \text{Post-baseline treatment assignment}\\
\end{align*}

Here we assume both $L_{t}$ and $A_{t}$ are discrete.

* Single time point strategy
** Title Single time point strategy
   :PROPERTIES:
   :BEAMER_ENV: fullframe
   :END:
#+BEGIN_CENTER
\resizebox{\linewidth}{!}{Single time point strategy}
#+END_CENTER

** Identifiability Conditions
- We will follow the terminologies in cite:hernanCausalInference2019 (Chapter 3).
1. *Consistency*: the values of treatment under comparison correspond to well-defined interventions that, in turn, correspond to the versions of treatment in the data
#+BEGIN_CENTER
$Y_{i} = Y_{i}^{a_{0}}$ if $A_{0i} = a_{0}$
#+END_CENTER
2. *Exchangeability*: the conditional probability of receiving every value of treatment, though not decided by the investigators, depends only on the measured covariates
#+BEGIN_CENTER
$Y_{i} = Y_{i}^{a_{0}}$ if $A_{0i} = a_{0}$
#+END_CENTER
3. *Positivity*: the conditional probability of receiving every value of treatment is greater than zero, i.e., positive

Equivalence Technical Point 2.3

** Identifiability Conditions (Math)
1. *Consistency*:
#+BEGIN_CENTER
$Y_{i} = Y_{i}^{a_{0}}$ if $A_{0i} = a_{0}$
#+END_CENTER
2. *Exchangeability*:
#+BEGIN_CENTER
$Y_{i} = Y_{i}^{a_{0}}$ if $A_{0i} = a_{0}$
#+END_CENTER
3. *Positivity*:
#+BEGIN_CENTER
$Y_{i} = Y_{i}^{a_{0}}$ if $A_{0i} = a_{0}$
#+END_CENTER

** G-formula
   :PROPERTIES:
   :BEAMER_opt: allowframebreaks,label=,t
   :END:
This follows the Technical Point 2.3 in cite:hernanCausalInference2019.
\begin{align*}
  &~~~\text{By iterative expectation}\\
  E[Y^{a_{0}}]
  &= E[E[Y^{a_{0}} | L_{0}]]\\
  &~~~\text{By conditional exchangeability: } Y^{a_{0}} \ind A_{0} | L_{0}\\
  &= E[E[Y^{a_{0}} | A_{0}, L_{0}]]\\
  &~~~\text{By exchangeability, }E[Y^{a_{0}} | A_{0}, L_{0}] = E[Y^{a_{0}} | A_{0} = a_{0}, L_{0}]\\
  &= E[E[Y^{a_{0}} | A_{0} = a_{0}, L_{0}]]\\
  &~~~\text{By consistency}\\
  &= E[E[Y | A_{0} = a_{0}, L_{0}]]\\
\end{align*}

** IPTW
   :PROPERTIES:
   :BEAMER_opt: allowframebreaks,label=,t
   :END:
This follows the Technical Point 2.3 in cite:hernanCausalInference2019.
\begin{align*}
  &~~~\text{By iterative expectation}\\
  E[Y^{a_{0}}]
  &= E[E[Y^{a_{0}} | L_{0}]]\\
  &~~~\text{Insert a carefully-crafted expression that is 1.}\\
  &= E \left[ \frac{f(A_{0}=a_{0} | L_{0})}{f(A_{0}=a_{0} | L_{0})} E[Y^{a_{0}} | L_{0}] \right]\\
  &~~~\text{Using probability = expectation of indicator}\\
  &= E \left[ \frac{E[I(A_{0}=a_{0}) | L_{0}]}{f(A_{0}=a_{0} | L_{0})} E[Y^{a_{0}} | L_{0}] \right]\\
  &~~~\text{Conditional exchangeability: } Y^{a_{0}} \ind A_{0} | L_{0}\\
  &~~~\text{This allows merging the two inner expectations.}\\
  &= E \left[ \frac{1}{f(A_{0}=a_{0} | L_{0})} E[I(A_{0}=a_{0})Y^{a_{0}} | L_{0}] \right]\\
  &~~~\text{By stability, } g(L_{0}) = E[g(L_{0}) | L_{0}].\\
  &~~~\text{i.e., a function of $L_{0}$ can go into $E[\cdot | L_{0}]$}\\
  &= E \left[ E \left[ \frac{1}{f(A_{0}=a_{0} | L_{0})} I(A_{0}=a_{0})Y^{a_{0}} \bigg| L_{0} \right] \right]\\
  &~~~\text{Reversing iterative expectation}\\
  &= E \left[ \frac{1}{f(A_{0}=a_{0} | L_{0})} I(A_{0}=a_{0})Y^{a_{0}} \right]\\
  &~~~\text{By consistency, }I(A_{0}=a_{0})Y^{a_{0}} = I(A_{0}=a_{0})Y = Y \text{ for } A_{0} = a_{0}.\\
  &~~~\text{Also, }I(A_{0}=a_{0})Y^{a_{0}} = 0 = I(A_{0}=a_{0})Y \text{ for } A_{0} \ne a_{0}.\\
  &~~~\text{Thus, }I(A_{0}=a_{0})Y^{a_{0}} = I(A_{0}=a_{0})Y \text{ regardless of } A_{0}.\\
  &= E \left[ \frac{1}{f(A_{0}=a_{0} | L_{0})} I(A_{0}=a_{0})Y \right]\\
  &= \text{IPTW estimand for group $A_{0} = a_{0}$}\\
\end{align*}

- Law of Total Expectation (Iterative Expectation): https://en.wikipedia.org/wiki/Law_of_total_expectation
- Stability and Tower Property: https://en.wikipedia.org/wiki/Conditional_expectation#Basic_properties
- Indicator function: https://www.statlect.com/fundamentals-of-probability/indicator-functions

* Multiple time point strategy


* Bibliography Part
** Bibliography
   :PROPERTIES:
   :BEAMER_opt: allowframebreaks,label=,t
   :END:
\tiny
# To remove "References" section header
\renewcommand{\section}[2]{}
# Following lines must be left-aligned without preceding spaces.
bibliographystyle:apalike
bibliography:~/.emacs.d/misc/zotero.bib
